import './css/modern-normalize.css';
import './css/styles.css';
import './css/feedback.css';
import './js/order-modal.js';
import './js/furniture-modal.js';
import './js/header.js';
import './js/furniture-list.js';
import './js/faq.js';
import './js/feedback.js';
